name: CI/CD Pipeline

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #récupère tout l'historique git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t devsecure-api .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "devsecure-api"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"

      - name: Run Snyk Scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: devsecure-api:latest
          args: --file=Dockerfile --json-file-output=snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Generate HTML report
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.html

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker tag devsecure-api ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
